"""Stage registry for the basketball analysis pipeline.

THE CONTRACT (implement your stage against this; do NOT edit this file)
=======================================================================

Every pipeline stage name below is pre-registered and maps to a lazy import
path ``"<module>:<attr>"``. To implement a stage, create/extend the mapped
module and define::

    def run_stage(ctx: StageContext) -> None: ...

Nothing else is required — no registration call, no edit to this file. A
stage counts as *implemented* the moment its module imports cleanly and
exposes the attribute; until then invoking it raises ``NotImplementedError``.

Registered stages, in pipeline order:

    decode    -> libs.basketball.video:run_stage      (implemented, Epic 1)
    scorebug  -> libs.basketball.scorebug:run_stage   (Epic 2)
    detect    -> libs.basketball.detect:run_stage     (Epic 2)
    shots     -> libs.basketball.shots:run_stage      (Epic 2)
    teams     -> libs.basketball.teams:run_stage      (Epic 3)
    jersey    -> libs.basketball.jersey:run_stage     (Epic 3)
    fuse      -> libs.basketball.timeline:run_stage   (Epic 2+; timeline.py
                                                       holds the event model)
    narrate   -> libs.basketball.narrate:run_stage    (Epic 4)

What ``run_stage`` receives — ``StageContext`` fields:

    ctx.stage       str                 name this stage was invoked under
    ctx.clip_path   Path                absolute path to the input clip
    ctx.clip_id     str                 "<stem>-<8-char sha256 prefix>"
    ctx.settings    BasketballSettings  config (libs.basketball.config)
    ctx.cache       ClipCache           per-clip cache (libs.basketball.cache)
    ctx.force       bool                True -> recompute even if warm
    ctx.pipeline    bool                True -> part of the CLI's default
                                        full-pipeline sweep; stages may then
                                        degrade gracefully instead of raising
                                        (e.g. detect with no configured model
                                        writes a {"skipped": true} marker).
                                        Direct/--stage invocations keep the
                                        default False and fail loudly.

What ``run_stage`` must do:

* Write its structured result via ``ctx.cache.write_json(ctx.stage, data)``
  as its LAST cache write — ``output.json`` existing is the "warm" marker
  (``ctx.cache.is_warm(name)``), so it must only appear once the stage's
  other artifacts (npz, crops, ...) are complete.
* Read upstream results via ``ctx.cache.read_json("<stage>")`` /
  ``ctx.cache.read_arrays("<stage>", <filename>)``; store arrays via
  ``ctx.cache.write_arrays(ctx.stage, {...})`` and arbitrary files under
  ``ctx.cache.path(ctx.stage, <filename>)``.
* Decode video via ``libs.basketball.video`` (``sample_frames`` /
  ``decode_window``) — timestamps always from PTS. Frames are NOT cached;
  re-decode on demand.
* Raise on unrecoverable errors; the CLI reports and exits non-zero. Do not
  call ``sys.exit`` from a stage.
* The ``fuse`` stage's ``output.json`` must be the predictions format of
  ``libs.basketball.timeline`` (``{"clip_id": ..., "events": [...]}``, events
  serialized via ``Event.to_dict``) — the CLI emits it verbatim and
  ``evals/basketball/run_eval.py`` consumes it.

Cache layout (see libs/basketball/cache.py):

    <workdir>/<clip_id>/<stage>/output.json   + optional npz/other artifacts
"""

import importlib
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List

from libs.basketball.cache import ClipCache
from libs.basketball.config import BasketballSettings

# Pipeline order matters: the CLI's default run executes stages in this order.
STAGE_ORDER: List[str] = [
    "decode",
    "scorebug",
    "detect",
    "shots",
    "teams",
    "jersey",
    "fuse",
    "narrate",
]

# name -> "module:attr" lazy import path. Pre-registered for ALL planned
# stages; implementing a stage never requires touching this table.
STAGE_REGISTRY: Dict[str, str] = {
    "decode": "libs.basketball.video:run_stage",
    "scorebug": "libs.basketball.scorebug:run_stage",
    "detect": "libs.basketball.detect:run_stage",
    "shots": "libs.basketball.shots:run_stage",
    "teams": "libs.basketball.teams:run_stage",
    "jersey": "libs.basketball.jersey:run_stage",
    "fuse": "libs.basketball.timeline:run_stage",
    "narrate": "libs.basketball.narrate:run_stage",
}


@dataclass
class StageContext:
    """Everything a stage needs: clip, config, and cached upstream outputs."""

    stage: str
    clip_path: Path
    clip_id: str
    settings: BasketballSettings
    cache: ClipCache
    force: bool = False
    pipeline: bool = False  # True only in the CLI's default full-pipeline sweep


def resolve_stage(name: str) -> Callable[[StageContext], None]:
    """Resolve a registered stage name to its ``run_stage`` callable.

    Raises KeyError for unknown names and NotImplementedError when the
    stage's module or ``run_stage`` attribute does not exist yet.
    """
    if name not in STAGE_REGISTRY:
        raise KeyError(f"Unknown stage '{name}'. Registered stages: {', '.join(STAGE_ORDER)}")
    target = STAGE_REGISTRY[name]
    module_name, attr = target.split(":")
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        raise NotImplementedError(
            f"Stage '{name}' is not implemented yet: module '{module_name}' does not exist. "
            f"Implement it by creating {module_name.replace('.', '/')}.py with a "
            f"'{attr}(ctx: StageContext) -> None' function (see libs/basketball/stages.py docstring)."
        ) from exc
    func = getattr(module, attr, None)
    if func is None:
        raise NotImplementedError(
            f"Stage '{name}' is not implemented yet: '{module_name}' has no '{attr}'. "
            f"Add '{attr}(ctx: StageContext) -> None' to it (see libs/basketball/stages.py docstring)."
        )
    return func


def is_implemented(name: str) -> bool:
    """True if the stage can be resolved to a callable right now."""
    try:
        resolve_stage(name)
    except NotImplementedError:
        return False
    return True


def run_stage_by_name(name: str, ctx: StageContext) -> None:
    """Resolve and execute one stage."""
    resolve_stage(name)(ctx)


def make_context(
    stage: str,
    clip_path: Path,
    clip_id: str,
    settings: BasketballSettings,
    workdir: Path,
    force: bool = False,
    pipeline: bool = False,
) -> StageContext:
    """Build the StageContext the CLI hands to each stage."""
    return StageContext(
        stage=stage,
        clip_path=clip_path,
        clip_id=clip_id,
        settings=settings,
        cache=ClipCache(workdir, clip_id),
        force=force,
        pipeline=pipeline,
    )
